import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const HEADER_COLOR  = [15, 31, 61]   // Navy
const ACCENT_COLOR  = [201, 151, 58] // Gold
const TEXT_COLOR    = [31, 41, 55]

function addMCROHeader(doc, title, subtitle = '') {
  // Gold top bar
  doc.setFillColor(...ACCENT_COLOR)
  doc.rect(0, 0, doc.internal.pageSize.width, 8, 'F')

  // Navy header band
  doc.setFillColor(...HEADER_COLOR)
  doc.rect(0, 8, doc.internal.pageSize.width, 38, 'F')

  // Title
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('MUNICIPAL CIVIL REGISTRAR\'S OFFICE', 14, 24)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('General Luna, Quezon | Republic of the Philippines', 14, 31)

  // Report title on right
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  const pw = doc.internal.pageSize.width
  doc.text(title.toUpperCase(), pw - 14, 22, { align: 'right' })
  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.text(subtitle, pw - 14, 30, { align: 'right' })
  }

  // Reset
  doc.setTextColor(...TEXT_COLOR)
  return 54 // Y after header
}

function addFooter(doc, pageNum, totalPages) {
  const pw = doc.internal.pageSize.width
  const ph = doc.internal.pageSize.height
  doc.setDrawColor(...ACCENT_COLOR)
  doc.setLineWidth(0.5)
  doc.line(14, ph - 18, pw - 14, ph - 18)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(100)
  doc.text('Generated by MCRO-CRMS', 14, ph - 10)
  doc.text(`Page ${pageNum} of ${totalPages}`, pw - 14, ph - 10, { align: 'right' })
  doc.text(new Date().toLocaleString('en-PH', { timeZone: 'Asia/Manila' }), pw / 2, ph - 10, { align: 'center' })
}

export function exportRecordsPDF(records, title = 'Records Export', subtitle = '') {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const startY = addMCROHeader(doc, title, subtitle)

  const cols = [
    { header: '#', dataKey: 'num' },
    { header: 'Date & Time', dataKey: 'date' },
    { header: 'Client Name', dataKey: 'client' },
    { header: 'Sex', dataKey: 'sex' },
    { header: 'Address', dataKey: 'address' },
    { header: 'Mobile', dataKey: 'mobile' },
    { header: 'Transaction Type', dataKey: 'type' },
    { header: 'Document Owner', dataKey: 'owner' },
    { header: 'Status', dataKey: 'status' },
  ]

  const rows = records.map((r, i) => ({
    num: i + 1,
    date: new Date(r.date).toLocaleString('en-PH', { timeZone: 'Asia/Manila', dateStyle: 'short', timeStyle: 'short' }),
    client: r.client_name,
    sex: r.sex || '—',
    address: r.address || '—',
    mobile: r.mobile_number || '—',
    type: r.transaction_type,
    owner: r.document_owner_name || '—',
    status: r.status,
  }))

  autoTable(doc, {
    startY,
    columns: cols,
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontStyle: 'bold', fontSize: 7 },
    bodyStyles: { fontSize: 7, textColor: TEXT_COLOR },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: { 0: { cellWidth: 8 }, 7: { cellWidth: 35 } },
    margin: { top: startY, left: 14, right: 14 },
    didDrawPage: (data) => {
      addFooter(doc, data.pageNumber, doc.getNumberOfPages())
    },
  })

  // Summary row
  const finalY = doc.lastAutoTable.finalY + 8
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text(`Total Records: ${records.length}`, 14, finalY)
  const pending    = records.filter(r => r.status === 'Pending').length
  const processing = records.filter(r => r.status === 'Processing').length
  const completed  = records.filter(r => r.status === 'Completed').length
  doc.setFont('helvetica', 'normal')
  doc.text(`Pending: ${pending}   Processing: ${processing}   Completed: ${completed}`, 14, finalY + 6)

  doc.save(`MCRO_${title.replace(/\s/g, '_')}.pdf`)
}

export function exportSummaryReport(data, title, subtitle) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const startY = addMCROHeader(doc, title, subtitle)

  // Totals table
  autoTable(doc, {
    startY: startY + 4,
    head: [['Metric', 'Count']],
    body: data.summary,
    theme: 'striped',
    headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontStyle: 'bold' },
    bodyStyles: { fontSize: 10 },
    margin: { left: 14, right: 14 },
  })

  if (data.byType?.length) {
    const y2 = doc.lastAutoTable.finalY + 10
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text('Breakdown by Transaction Type', 14, y2)
    autoTable(doc, {
      startY: y2 + 4,
      head: [['Transaction Type', 'Count']],
      body: data.byType,
      theme: 'striped',
      headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontStyle: 'bold' },
      bodyStyles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
      didDrawPage: (d) => addFooter(doc, d.pageNumber, doc.getNumberOfPages()),
    })
  }

  addFooter(doc, 1, doc.getNumberOfPages())
  doc.save(`MCRO_${title.replace(/\s/g, '_')}.pdf`)
}
